INSERT INTO categoria (id, descrizione) VALUES (1, 'Elettronica');
INSERT INTO categoria (id, descrizione) VALUES (2, 'Abbigliamento ');
INSERT INTO categoria (id, descrizione) VALUES (3, 'Casa');
INSERT INTO categoria (id, descrizione) VALUES (4, 'Sport e tempo libero');
INSERT INTO categoria (id, descrizione) VALUES (5, 'Salute e bellezza');
INSERT INTO categoria (id, descrizione) VALUES (6, 'Libri, film e musica');
INSERT INTO categoria (id, descrizione) VALUES (7, 'Giochi e giocattoli');
INSERT INTO categoria (id, descrizione) VALUES (8, 'Articoli per animali domestici');
INSERT INTO categoria (id, descrizione) VALUES (9, 'Ufficio');
INSERT INTO categoria (id, descrizione) VALUES (10, 'Artigianato e prodotti fatti a mano');
INSERT INTO categoria (id, descrizione) VALUES (11, 'Telefonia');
INSERT INTO categoria (id, descrizione) VALUES (12, 'Computer e accessori');
INSERT INTO categoria (id, descrizione) VALUES (13, 'Elettrodomestici');
INSERT INTO categoria (id, descrizione) VALUES (14, 'TV e audio');
INSERT INTO categoria (id, descrizione) VALUES (15, 'Scarpe');
INSERT INTO categoria (id, descrizione) VALUES (16, 'Arredamento');
INSERT INTO categoria (id, descrizione) VALUES (17, 'Cucina');
INSERT INTO categoria (id, descrizione) VALUES (18, 'Giardinaggio');
INSERT INTO categoria (id, descrizione) VALUES (19, 'Strumenti musicali');
